language: erlang
otp_release:
  - R15B01
  - R14B04
script: make clean test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
