#!/bin/sh -e

### BEGIN INIT INFO
# Provides:             zotonic
# Required-Start:       $postgres $local_fs $remote_fs $network $time
# Required-Stop:        $postgres $local_fs $remote_fs $network $time
# Should-Start:         
# Should-Stop:          
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Zotonic
### END INIT INFO

/usr/bin/sudo -u zotonic SNAME=zotonic001 -i /var/lib/zotonic/zotonic/bin/zotonic $*
